version: '3'
services:
  server:
    container_name: server_api
    
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    links:
      - mongo


  mongo:
    container_name: mongo
    image: mongo
    ports:
    - 27017:27017
    volumes:
     - ./mongodb:/data/db
    
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports: 
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    links:
    - server
  
  


